version: "3"
services:
    kumi-app:
        build: .
        image: kumigernhardt/hello-world-imag 
        ports: 
            - "3000:3000"
        volumes:
            - ./:/app 
            - /app/node_modules
        environment: 
            - PORT=3000

